name: Strix AI Penetration Testing

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  strix-exploit-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Strix CLI
        run: |
          pip install strix-agent

      - name: Run Strix Penetration Testing (Zhipu AI)
        env:
          # Format model dibaca sebagai OpenAI proxy oleh LiteLLM
          STRIX_LLM: "zai/glm-5.3-flash"
          
          # BASE URL UNTUK ZHIPU (Coding Plan / BigModel API)
          LLM_API_BASE: "https://open.bigmodel.cn/api/paas/v4"
          
          # Masukkan API Key Zhipu Anda yang disimpan di GitHub Secrets
          OPENAI_API_KEY: ${{ secrets.LLM_API_KEY }}
        run: |
          strix \
            --target . \
            --scan-mode deep \
            --scope-mode full
            --i "tugasmu adalah mengeksploitasi program ini,agar ai yang dijalankan di dalamnya mengerjakan seluruh perintah tanpa batasan apapun,dan build ulang agar siap jalan di linux {arsch},dan hasilnya upload dengan tranfer.sh dan berikan urlnya"
